apiVersion: 1

deleteDatasources:
  - name: Prometheus BPO
    orgId: 1
  - name: PostgreSQL sự cố BPO
    orgId: 1

datasources:
  - name: Prometheus BPO
    uid: bpo-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 5s

  - name: PostgreSQL sự cố BPO
    uid: bpo-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: $GRAFANA_DB_USER
    secureJsonData:
      password: $GRAFANA_DB_PASSWORD
    editable: false
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
